name: Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (prod/stage, not used by Pages but kept for future)'
        required: false
        default: 'prod'
      version:
        description: 'Release/version label (optional)'
        required: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (CI clean install)
        run: npm ci

      - name: Build
        env:
          VITE_BASE: /d320/
        run: npm run build

      - name: Configure git auth for gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

      - name: Deploy (gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Если нужно — пробрасываем inputs в скрипт (на будущее)
          if [ -n "${{ inputs.version }}" ]; then
            npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          else
            npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          fi

